# Generated by Django 4.2.1 on 2023-05-24 13:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish', verbose_name='slug')),
                ('excerpt', models.CharField(max_length=250, verbose_name='excerpt')),
                ('body', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=300, message='Content should be at least 300 characters long!')], verbose_name='body')),
                ('image', models.ImageField(upload_to='posts_images', verbose_name='image')),
                ('image_caption', models.CharField(blank=True, max_length=50, verbose_name='image caption')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=2)),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='page views')),
                ('read_time', models.PositiveIntegerField(default=0, help_text='Estimated time taken to read the post.', verbose_name='read time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='news.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-publish'],
                'get_latest_by': 'publish',
                'indexes': [models.Index(fields=['-publish'], name='news_post_publish_fb80b2_idx')],
            },
        ),
    ]
