# Generated by Django 4.2.1 on 2023-06-01 00:46

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.SmallIntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, unique_for_date='created', verbose_name='slug')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(validators=[django.core.validators.MinLengthValidator(limit_value=300, message='Content should be at least 300 characters long!')], verbose_name='body')),
                ('image', models.ImageField(default='post.png', upload_to='posts_images', verbose_name='image')),
                ('image_caption', models.CharField(blank=True, max_length=50, verbose_name='image caption')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='page views')),
                ('read_time', models.PositiveIntegerField(default=0, help_text='Estimated time taken to read the post.', verbose_name='read time')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='news.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'indexes': [models.Index(fields=['-created'], name='news_post_created_06702a_idx')],
            },
        ),
    ]
