# Generated by Django 4.2.1 on 2023-06-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
