# Generated by Django 4.2.1 on 2023-05-25 01:07

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_options_remove_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(validators=[django.core.validators.MinLengthValidator(limit_value=300, message='Content should be at least 300 characters long!')], verbose_name='body'),
        ),
    ]
