# Generated by Django 4.2.1 on 2023-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images', verbose_name='image'),
        ),
    ]
