# Generated by Django 4.2.1 on 2023-06-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_image_link_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, help_text='Enter Image URL here.', null=True),
        ),
    ]
