# Generated by Django 4.2.1 on 2023-05-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_category_options_category_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
